import Tooltip from '../tooltip'

export interface BandChartProps {
  bgFill: string
  // generated by chromajs scale
  itemWidth: number
  // percentage of total
  category: string
}

export function BandChart({ bgFill, itemWidth, category }: BandChartProps) {
  return (
    <span
      key={category}
      className='flex h-5 w-[340px] flex-row items-center justify-center font-semibold'
      style={{
        backgroundColor: `${bgFill}`,
        width: `${itemWidth}%`
      }}
    >
      <Tooltip message={category}>
        <p className='space-between flex text-[12px] text-black'>
          {itemWidth}%{' '}
        </p>
      </Tooltip>
    </span>
  )
}
